version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - run: yarn lint
      - run: yarn coverage
