version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run: yarn install
  test:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
        name: Lint test + Unit test
        command: "yarn lint"
      - run:
        name: Unit test
        command: "yarn test"
      - run:
        name: Generate code coverage
        command: "yarn coverage"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
